import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

   default: [
      'quickstart',
      {
           type: 'category',
           label: 'Smart contracts',
           link: {
                type: 'doc',
                id: 'smart-contract-dev',
           },
           items: [

                'smart-contracts/get-started-intro',
                {
                  type: 'category',
                  label: 'Installation and setup',
                  link: {
                     type: 'doc',
                     id: 'smart-contracts/install',
                   },
                 items: [
                  'smart-contracts/install/linux',
                  'smart-contracts/install/macos',
                  'smart-contracts/install/windows',
                  'smart-contracts/install/tooling',
                  'smart-contracts/install/local-dev-node',
                 ],
                },
                'smart-contracts/basic-concepts',
                'smart-contracts/accounts',
                'smart-contracts/lang-features',
                'smart-contracts/functions-variables',
                'smart-contracts/modules',
                'smart-contracts/capabilities',
                'smart-contracts/guards',
                'smart-contracts/databases',
                'smart-contracts/transactions',
                ],
      },
      {
         type: 'category',
         label: 'How-to guides',
         link: {
              type: 'doc',
              id: 'guides/guides',
         },
         items: [
            {
               type: 'category',
               label: 'Accounts',
               items: [
                'guides/accounts/howto-create-accounts',
                'guides/accounts/howto-fund-accounts',
                'guides/accounts/howto-get-balances',
                'guides/accounts/howto-rotate-owners',
                'guides/accounts/howto-safe-transfers',
               ],
            },
            {
               type: 'category',
               label: 'Contracts',
               items: [
                'guides/contracts/howto-read-state',
                'guides/contracts/howto-deploy-contracts',
                'guides/contracts/howto-call-functions',
               ],
            },
            {
               type: 'category',
               label: 'Transactions',
               items: [
                'guides/transactions/howto-construct-tx',
                'guides/transactions/howto-sign-submit-tx',
                'guides/transactions/howto-check-tx-status',
                'guides/transactions/howto-verify-signatures',
               ],
            },
            {
                type: 'category',
                label: 'Nodes',
                link: {
                   type: 'doc',
                   id: 'guides/nodes/nodes',
              },
                 items: [
                     'guides/nodes/compact-databases',
                     'guides/nodes/configure',
                     'guides/nodes/monitoring',
              ],
           },
         ],
      },
      {
         type: 'category',
         label: 'API',
         link: {
           type: 'doc',
           id: 'api/api',
         },
         items: [
            {
                 type: 'category',
                 label: 'Pact API',
                 link: {
                      type: 'doc',
                      id: 'api/pact-api/pact-api',
                 },
                 items: [
                      "api/pact-api/listen",
                      "api/pact-api/local",
                      "api/pact-api/poll",
                      "api/pact-api/private",
                      "api/pact-api/send",
                      "api/pact-api/spv",
                 ],
            },
            {
                 type: 'category',
                 label: 'Peer-to-peer API',
                 link: {
                      type: 'doc',
                      id: 'api/peer-to-peer/p2p-api',
                 },
                 items: [
                      "api/peer-to-peer/get-cut",
                      "api/peer-to-peer/publish-cut",
                      "api/peer-to-peer/get-payload",
                      "api/peer-to-peer/all-pending-mempool",
                      "api/peer-to-peer/boolean-tx-mempool",
                      "api/peer-to-peer/lookup-tx-mempool",
                      "api/peer-to-peer/insert-tx-mempool",
                      "api/peer-to-peer/api-get-cut-peers",
                      "api/peer-to-peer/api-add-cut-peers",
                      "api/peer-to-peer/api-get-mempool-peers",
                      "api/peer-to-peer/api-add-mempool-peers",
                      "api/peer-to-peer/api-config",
                 ],
            },
            {
                 type: "category",
                 label: "Service API",
                 link: {
                      type: "doc",
                      id: "api/service-api/service-api",
                      },
                      items: [
                           "api/service-api/get-block",
                           "api/service-api/get-block-branch",
                           "api/service-api/get-block-hash",
                           "api/service-api/get-block-hash-branch",
                           "api/service-api/get-block-header",
                           "api/service-api/get-block-header-by-hash",
                           "api/service-api/get-block-header-branch",
                           'api/service-api/api-update-event-stream',
                           'api/service-api/make-db-backup',
                           'api/service-api/check-db-backup',
                           'api/service-api/check-node-health',
                           'api/service-api/get-node-info',
                           'api/service-api/mining',
                           'api/service-api/rosetta',
                      ],
            },
            'api/data-models',
            'api/binary-encoding',
       ],
  },
  {
      type: 'category',
      label: 'Reference',
      link: {
         type: 'doc',
         id: 'reference/reference',
      },
      items: [
         'reference/syntax',
         'pact-5/func-quick-ref',
         {
            type: 'category',
            label: 'Capability functions',
            link: {
               type: 'doc',
               id: 'pact-5/Capabilities/0-capability',
            },
            items: [
               'pact-5/Capabilities/compose-capability',
               'pact-5/Capabilities/emit-event',
               'pact-5/Capabilities/install-capability',
               'pact-5/Capabilities/require-capability',
               'pact-5/Capabilities/with-capability',
               ],
         },
         {
            type: 'category',
            label: 'Database functions',
            link: {
               type: 'doc',
               id: 'pact-5/Database/0-database',
            },
            items: [
               'pact-5/Database/create-table',
               'pact-5/Database/describe-keyset',
               'pact-5/Database/describe-module',
               'pact-5/Database/describe-table',
               'pact-5/Database/fold-db',
               'pact-5/Database/insert',
               'pact-5/Database/keylog',
               'pact-5/Database/keys',
               'pact-5/Database/list-modules',
               'pact-5/Database/read',
               'pact-5/Database/select',
               'pact-5/Database/txids',
               'pact-5/Database/txlog',
               'pact-5/Database/update',
               'pact-5/Database/with-default-read',
               'pact-5/Database/with-read',
               'pact-5/Database/write',
            ],
         },
         {
            type: 'category',
            label: 'General functions',
            link: {
               type: 'doc',
               id: 'pact-5/General/0-general',
            },
            items: [
               'pact-5/General/acquire-module-admin',
               'pact-5/General/at',
               'pact-5/General/base64-decode',
               'pact-5/General/base64-encode',
               'pact-5/General/bind',
               'pact-5/General/chain-data',
               'pact-5/General/charset-ascii',
               'pact-5/General/charset-latin1',
               'pact-5/General/compose',
               'pact-5/General/concat',
               'pact-5/General/constantly',
               'pact-5/General/contains',
               'pact-5/General/define-namespace',
               'pact-5/General/describe-namespace',
               'pact-5/General/distinct',
               'pact-5/General/drop',
               'pact-5/General/enforce-guard',
               'pact-5/General/enforce-one',
               'pact-5/General/enforce-pact-version',
               'pact-5/General/enforce-verifier',
               'pact-5/General/enforce',
               'pact-5/General/filter',
               'pact-5/General/fold',
               'pact-5/General/format',
               'pact-5/General/hash-keccak256',
               'pact-5/General/hash',
               'pact-5/General/identity',
               'pact-5/General/if',
               'pact-5/General/int-to-str',
               'pact-5/General/is-charset',
               'pact-5/General/length',
               'pact-5/General/list-module',
               'pact-5/General/list',
               'pact-5/General/make-list',
               'pact-5/General/map',
               'pact-5/General/namespace',
               'pact-5/General/pact-id',
               'pact-5/General/pact-version',
               'pact-5/General/poseidon-hash-hack-a-chain',
               'pact-5/General/read-decimal',
               'pact-5/General/read-integer',
               'pact-5/General/read-keyset',
               'pact-5/General/read-msg',
               'pact-5/General/read-string',
               'pact-5/General/remove',
               'pact-5/General/resume',
               'pact-5/General/reverse',
               'pact-5/General/round',
               'pact-5/General/sort',
               'pact-5/General/static-redeploy',
               'pact-5/General/str-to-int',
               'pact-5/General/str-to-list',
               'pact-5/General/take',
               'pact-5/General/try',
               'pact-5/General/tx-hash',
               'pact-5/General/typeof',
               'pact-5/General/where',
               'pact-5/General/yield',
               'pact-5/General/zip',
            ],
         },
         {
            type: 'category',
            label: 'Guard functions',
            link: {
               type: 'doc',
               id: 'pact-5/Guards/0-guards',
            },
            items: [
               'pact-5/Guards/create-capability-guard',
               'pact-5/Guards/create-capability-pact-guard',
               'pact-5/Guards/create-module-guard',
               'pact-5/Guards/create-pact-guard',
               'pact-5/Guards/create-principal',
               'pact-5/Guards/create-user-guard',
               'pact-5/Guards/is-principal',
               'pact-5/Guards/keyset-ref-guard',
               'pact-5/Guards/typeof-principal',
               'pact-5/Guards/validate-principal',
            ]
         },
         {
            type: 'category',
            label: 'Keyset functions',
            link: {
               type: 'doc',
               id: 'pact-5/Keysets/0-keysets',
            },
            items: [
               'pact-5/Keysets/define-keyset',
               'pact-5/Keysets/enforce-keyset',
               'pact-5/Keysets/keys-2',
               'pact-5/Keysets/keys-all',
               'pact-5/Keysets/keys',
            ]
         },
         {
            type: 'category',
            label: 'Operator functions',
            link: {
               type: 'doc',
               id: 'pact-5/Operators/0-operators',
            },
            items: [
               'pact-5/Operators/abs',
               'pact-5/Operators/add',
               'pact-5/Operators/and-q',
               'pact-5/Operators/and',
               'pact-5/Operators/bitwise-and',
               'pact-5/Operators/bitwise-or',
               'pact-5/Operators/bitwise-reverse',
               'pact-5/Operators/ceiling',
               'pact-5/Operators/dec',
               'pact-5/Operators/div',
               'pact-5/Operators/eq',
               'pact-5/Operators/exp',
               'pact-5/Operators/floor',
               'pact-5/Operators/geq',
               'pact-5/Operators/gt',
               'pact-5/Operators/leq',
               'pact-5/Operators/ln',
               'pact-5/Operators/log',
               'pact-5/Operators/lt',
               'pact-5/Operators/mod',
               'pact-5/Operators/mult',
               'pact-5/Operators/neq',
               'pact-5/Operators/not-q',
               'pact-5/Operators/not',
               'pact-5/Operators/or-q',
               'pact-5/Operators/or',
               'pact-5/Operators/pow',
               'pact-5/Operators/shift',
               'pact-5/Operators/sqrt',
               'pact-5/Operators/sub',
               'pact-5/Operators/xor',
            ],
         },
         {
            type: 'category',
            label: 'REPL-only functions',
            link: {
               type: 'doc',
               id: 'pact-5/Repl/0-repl',
            },
            items: [
               'pact-5/Repl/begin-tx',
               'pact-5/Repl/commit-tx',
               'pact-5/Repl/continue-pact',
               'pact-5/Repl/env-chain-data',
               'pact-5/Repl/env-data',
               'pact-5/Repl/env-enable-repl-natives',
               'pact-5/Repl/env-events',
               'pact-5/Repl/env-exec-config',
               'pact-5/Repl/env-gas',
               'pact-5/Repl/env-gaslimit',
               'pact-5/Repl/env-gasmodel',
               'pact-5/Repl/env-hash',
               'pact-5/Repl/env-keys',
               'pact-5/Repl/env-namespace-policy',
               'pact-5/Repl/env-sigs',
               'pact-5/Repl/expect-failure',
               'pact-5/Repl/expect-that',
               'pact-5/Repl/expect',
            ]
         },
         {
            type: 'category',
            label: 'Time functions',
            link: {
               type: 'doc',
               id: 'pact-5/Time/0-time',
            },
            items: [
               'pact-5/Time/add-time',
               'pact-5/Time/days',
               'pact-5/Time/diff-time',
               'pact-5/Time/format-time',
               'pact-5/Time/hours',
               'pact-5/Time/minutes',
               'pact-5/Time/parse-time',
               'pact-5/Time/time',
            ]
         },
         {
            type: 'category',
            label: 'Specialized functions',
            link: {
               type: 'doc',
               id: 'pact-5/special-use',
            },
            items: [
               'pact-5/Commitments/decrypt-cc20p1305',
               'pact-5/Commitments/hyperlane-decode-token-message',
               'pact-5/Commitments/hyperlane-encode-token-message',
               'pact-5/Commitments/hyperlane-message-id',
               'pact-5/Commitments/validate-keypair',
               'pact-5/SPV/verify-spv',
               'pact-5/ZK/pairing-check',
               'pact-5/ZK/point-add',
               'pact-5/ZK/scalar-mult'
            ],
         },
      'reference/pact-cli',
      {
         type: 'category',
         label: 'kadena-cli commands',
         link: {
            type: 'doc',
            id: 'reference/kadena-cli',
         },
         items: [
            'reference/cli/cli-account',
            'reference/cli/cli-config',
            'reference/cli/cli-dapp',
            'reference/cli/cli-key',
            'reference/cli/cli-network',
            'reference/cli/cli-tx',
            'reference/cli/cli-wallet',
         ],
      },
         'reference/chainweb-cli',
         //'reference/client-libs',
         'reference/guard-json',
      ],
   },
      {
         type: 'category',
         label: 'Coding projects',
         link: {
         type: 'doc',
         id: 'coding-projects/coding-projects',
         },
         items: [
              'coding-projects/hello-world',
              'coding-projects/transfers',
              'coding-projects/rotate-auth',
              //'coding-projects/pact-testing',
              //'coding-projects/interaction',
              //'coding-projects/loans',
              ],
    },
    {
      type: 'category',
      label: 'Resources',
      link: {
           type: 'doc',
           id: 'resources/resources',
      },
      items: [
           // 'resources/changelogs',
           //'resources/contributors',
           'resources/glossary',
           'resources/contribute-doc',
           'resources/contribute-dev',
           'resources/writing-guide',
           //'resources/tools',
           /*{
                type: 'link',
                label: 'Product Docs',
                href: 'https://docs.kadena.io',
           },*/
      ],
 }
],

   solutions: [
      'solutions/solutions',
      {
         type: 'category',
         label: 'Block Explorer',
         items: [
            'solutions/block-explorer/block-explorer',
         ],
      },
      {
         type: 'category',
         label: 'Chainweaver Wallet',
         items: [
            'solutions/chainweaver/chainweaver',
         ],
      },
      {
         type: 'category',
         label: 'GraphQL',
         items: [
            'solutions/graphql/graphql',
         ],
      },
      {
         type: 'category',
         label: 'HD Wallet',
         items: [
            'solutions/hd-wallet/hd-wallet',
         ],
      },
      {
         type: 'category',
         label: 'KadenaJS',
         items: [
            'solutions/kadena-js/kadena-js',
         ],
      },
      {
         type: 'category',
         label: 'Kadena CLI',
         items: [
            'solutions/kadena-cli/kadena-cli',
         ],
      },
      {
         type: 'category',
         label: 'Marmalade',
         items: [
            'solutions/marmalade/marmalade',
         ],
      },
      {
         type: 'category',
         label: 'Spirekey Wallet',
         items: [
            'solutions/spirekey/spirekey',
         ],
      },
   ],
};

export default sidebars;